// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxr1gwjfedsXhIfM9EP10h4itFIaFKRqM',
    appId: '1:953433426515:android:0759e42f793b4b4c5714a6',
    messagingSenderId: '953433426515',
    projectId: 'musicalmelodies-db276',
    storageBucket: 'musicalmelodies-db276.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo8mFgF6cqaO2CpUVtR4kURKXPdY2FPfo',
    appId: '1:953433426515:ios:79668967f0533bc65714a6',
    messagingSenderId: '953433426515',
    projectId: 'musicalmelodies-db276',
    storageBucket: 'musicalmelodies-db276.appspot.com',
    androidClientId: '953433426515-dvdndqqhp0llhkv6qjs8ml222ki499ci.apps.googleusercontent.com',
    iosClientId: '953433426515-94olf0isfia13pv27tvdb6vhq4rahvis.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3NGnrke84ZjFLWsslQSoMwrTDIe5q5KU',
    appId: '1:953433426515:web:ba6c550c24a91bdc5714a6',
    messagingSenderId: '953433426515',
    projectId: 'musicalmelodies-db276',
    authDomain: 'musicalmelodies-db276.firebaseapp.com',
    storageBucket: 'musicalmelodies-db276.appspot.com',
    measurementId: 'G-HTBFBD60Y4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo8mFgF6cqaO2CpUVtR4kURKXPdY2FPfo',
    appId: '1:953433426515:ios:79668967f0533bc65714a6',
    messagingSenderId: '953433426515',
    projectId: 'musicalmelodies-db276',
    storageBucket: 'musicalmelodies-db276.appspot.com',
    androidClientId: '953433426515-dvdndqqhp0llhkv6qjs8ml222ki499ci.apps.googleusercontent.com',
    iosClientId: '953433426515-94olf0isfia13pv27tvdb6vhq4rahvis.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3NGnrke84ZjFLWsslQSoMwrTDIe5q5KU',
    appId: '1:953433426515:web:8e8af91c71a7f8775714a6',
    messagingSenderId: '953433426515',
    projectId: 'musicalmelodies-db276',
    authDomain: 'musicalmelodies-db276.firebaseapp.com',
    storageBucket: 'musicalmelodies-db276.appspot.com',
    measurementId: 'G-9PDWQDGKLY',
  );

}